Refactor parameters as a JSON Object
noamalffasy/js-whatsapp pull request #3
Opened 2020-04-12 23:02 UTC by csgt

Refactor parameters as a JSON Object, add clientName and clientShortName parameters.  Adds flexibility for future customizations.  Update README to reflect the changes.

2020-05-09 21:35 UTC, noamalffasy requested changes
That's a great suggestion, I'd change a few things (I added suggestions to them, you should be able to just agree to them and automatically update it).

In addition to them, I think that along with this change I should also update all of the methods and make them use JSON objects too.

I wanted to keep it for a later version so it wouldn't break existing code. However, since I'm bringing this one over now, I think that updating the functions should be done along with it.

What do you think of the suggestion?

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +    parameters = {}
```suggestion
    opts = {      
        keysPath: "./keys.json",
        qrPath: "./qrcode.png",
        clientName: "WhatsApp forwarder",
        clientShortName: "WhatsAppForwarder",
        restoreSession: false 
    }
```
Rewriting all the options later is unnecessary.

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +    }, ...parameters}
```suggestion
    this.opts = Object.assign({}, opts, this.opts);
```
It's more readable in my opinion and performs better (according to [this site](https://jsperf.com/comparing-object-asign-spread))

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +    this.parameters.qrPath = resolvePath(".", this.parameters.qrPath);
```suggestion
    this.opts.qrPath = resolvePath(".", this.opts.qrPath);
```
Update the property name

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +      this.parameters.keysPath = resolvePath(".", this.parameters.keysPath);
```suggestion
    if (this.opts.restoreSession) {
      this.opts.keysPath = resolvePath(".", this.opts.keysPath);
```
Update again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +    this.apiSocket.onopen = this.init(loginMsgId, this.parameters.restoreSession);
```suggestion
    this.apiSocket.onopen = this.init(loginMsgId, this.opts.restoreSession);
```
Update again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +      doesFileExist(this.parameters.keysPath!).then(doesExist => {
```suggestion
    if (this.opts.restoreSession) {
      doesFileExist(this.opts.keysPath!).then(doesExist => {
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +      this.parameters.keysPath!,
```suggestion
      this.opts.keysPath!,
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +      readFile(this.parameters.keysPath!, "utf-8", (err, data) => {
```suggestion
      readFile(this.opts.keysPath!, "utf-8", (err, data) => {
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +            if (this.parameters.keysPath) {
```suggestion
            if (this.opts.keysPath) {
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +            if (this.parameters.keysPath) {
```suggestion
            if (this.opts.keysPath) {
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +    writeFile(this.parameters.qrPath, qrCode.data, err => {
```suggestion
    writeFile(this.opts.qrPath, qrCode.data, err => {
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +        (restoreSession && !(await doesFileExist(this.parameters.keysPath!)))
```suggestion
        (restoreSession && !(await doesFileExist(this.opts.keysPath!)))
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +        `${loginMsgId},["admin","init",[0,4,2080],["${this.parameters.clientName}","${this.parameters.clientShortName}"],"${this.clientId}",true]`
```suggestion
        `${loginMsgId},["admin","init",[0,4,2080],["${this.opts.clientName}","${this.opts.clientShortName}"],"${this.clientId}",true]`
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +      if (restoreSession && (await doesFileExist(this.parameters.keysPath!))) {
```suggestion
      if (restoreSession && (await doesFileExist(this.opts.keysPath!))) {
```
Update property again

2020-05-09 21:35 UTC, noamalffasy commented on src/main.ts
> +  }
```suggestion
  private opts: {
    keysPath: string,
    qrPath: string,
    clientName: string,
    clientShortName: string,
    restoreSession: boolean
  }
```
Adjusting it to my preference and code style.

2020-05-09 21:35 UTC, noamalffasy commented on README.md
> +const wap = new Whatsapp(params);
```suggestion
const opts = {
  keysPath: "./keys.json",
  qrPath: "./qrcode.png",
  clientName: "WhatsApp forwarder",
  clientShortName: "WhatsAppForwarder",
  restoreSession: false
}

const wap = new Whatsapp(opts);
```
I'd change the name to this instead, just a preference.
I also changed the code style (no space before the` :` and after the property name).

2020-05-09 21:35 UTC, noamalffasy commented on README.md
> +const wap = new Whatsapp({restoreSession : true});
```suggestion
const wap = new Whatsapp({restoreSession: true});
```
Same code style

2020-05-11 00:35 UTC, csgt commented
Yeah, props looks fine.  Maybe tag a major version change so current users are not affected and apply the params to all functions!

2020-09-15 01:23 UTC, closed without merging